# Поддержка версии Python
target-version = "py311"

# Максимальная длина строки кода
line-length = 120

# Ширина отступа (количество пробелов)
indent-width = 4

# Игнорируемые пути (например, виртуальное окружение, виртуальные папки)
exclude = ["venv", ".venv", "build", "dist", "__pycache__"]

# Включенные правила (по умолчанию все включены, здесь пример явного указания)
select = [
  "E",  # Ошибки стиля (как в pycodestyle)
  "F",  # Ошибки импорта, синтаксиса, и другие
  "W",  # Предупреждения по стилю
  "C",  # Проверки сложности кода
  "N",  # Руководства по именованиям
  "D",  # Докстринг (pydocstyle)
]

# Иные настройки (например, переходы строк, добавочные аргументы)
# можно дополнить, если нужно
